FROM amazoncorretto:17
EXPOSE 8085
ADD target/Gestion_nettoyage_maintenance-1.0-SNAPSHOT.jar Gestion_nettoyage_maintenance-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","Gestion_nettoyage_maintenance-1.0-SNAPSHOT.jar"]