FROM amazoncorretto:17
EXPOSE 8082
ADD target/Gestion_avis_reclamations-1.0-SNAPSHOT.jar Gestion_avis_reclamations-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","Gestion_avis_reclamations-1.0-SNAPSHOT.jar"]