spring.cloud.bootstrap.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true


server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

server.servlet.context-path=/personnel/api

cloudinary.cloud_name=ddtfi7kal
cloudinary.api_key=971417699379591
cloudinary.api_secret=SzcF1Ll17RR2oMvueIXikFAN2IM

logging.level.feign=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.com.netflix.discovery=DEBUG
logging.level.com.netflix.loadbalancer=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG
