# ──────────────────────────────────────────────────────────
# DISCOVERY SERVICE (EUREKA) - CONFIGURATION CENTRALISÉE
# ──────────────────────────────────────────────────────────

# Application Identification
spring.application.name=registry-service

# Server Settings
server.port=8761

# Eureka Server Configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Actuator
management.endpoints.web.exposure.include=*
