# Configuration de la base de données (Déportée depuis Gestion_personnel)
spring.datasource.url=jdbc:mysql://localhost:3306/personnel?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Base_Securisee_123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Port du service
server.port=8086

# Configuration Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Logging & Error handling
server.error.include-message=always
server.error.include-stacktrace=always
logging.level.feign=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG

# Message de bienvenue personnalisé
welcome.message=Welcome to Gestion personnel (Configured by Config Server)

# Actuator
management.endpoints.web.exposure.include=*
