server.port=8888
spring.application.name=config-server

# Activation du mode natif pour lire les fichiers locaux
spring.profiles.active=native

# Chemin ABSOLU vers le dossier local pour éviter les erreurs 404 selon le contexte de lancement
spring.cloud.config.server.native.search-locations=file:///C:/Users/amirt/OneDrive/Desktop/App%20Web%20Dis%20Final/devunity-hotel-brise-douce-bouthayna/backend/Config_Server/config-repo

# Configuration Eureka : Désactivée pour le Config Server lui-même
# (Il est préférable qu'il soit indépendant pour éviter les erreurs si Eureka est éteint)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
