# Nom de l'application (Identifiant pour Eureka et Config Server)
spring.application.name=clients-service

# Importation de la configuration depuis le Config Server
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

# Préfixe d'URL (Context Path)
server.servlet.context-path=/clients/api

# Optionnel : Forcer le profil par défaut (peut-être ajusté au besoin)
spring.profiles.active=default